#!/usr/bin/env python3
"""
Generate Ansible inventory from config/lab.yml.

Reads server roles from lab config and writes
ansible/inventory/hosts.yml.

Run:
    python3 scripts/generate-inventory.py

Output: ansible/inventory/hosts.yml (overwrites existing file)
"""

import yaml
from pathlib import Path
import sys

ROOT = Path(__file__).parent.parent
LAB_CONFIG = ROOT / "config" / "lab.yml"
OUTPUT = ROOT / "ansible" / "inventory" / "hosts.yml"


def load_lab() -> dict:
    """Load lab.yml as a dictionary."""
    if not LAB_CONFIG.exists():
        print(f"ERROR: missing {LAB_CONFIG}", file=sys.stderr)
        sys.exit(1)
    with open(LAB_CONFIG, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def build_inventory(lab: dict) -> dict:
    """
    Build Ansible inventory from lab config.

    Role to Ansible group mapping:
        domain-controller  -> domain_controllers
        domain-member      -> member_servers
        dhcp-server        -> dhcp_servers
        file-server        -> file_servers
    """

    role_to_group = {
        "domain-controller": "domain_controllers",
        "domain-member":     "member_servers",
        "dhcp-server":       "dhcp_servers",
        "file-server":       "file_servers",
    }

    groups = {grp: {"hosts": {}} for grp in role_to_group.values()}

    windows_vars = {
        "ansible_connection":               "winrm",
        "ansible_winrm_transport":          "basic",
        "ansible_winrm_server_cert_validation": "ignore",
        "ansible_port":                     5985,
        "ansible_user":                     lab["local_admin"]["username"],
        "ansible_password":                 "Lab123",
    }

    for server in lab["servers"]:
        hostname = server["hostname"].lower()
        host_entry = {
            "ansible_host": server["ip"],
        }

        for role in server.get("roles", []):
            grp = role_to_group.get(role)
            if grp:
                groups[grp]["hosts"][hostname] = host_entry

    inventory = {
        "all": {
            "children": {
                "windows": {
                    "vars": windows_vars,
                    "children": {grp: groups[grp] for grp in groups if groups[grp]["hosts"]},
                }
            }
        }
    }

    return inventory


def main():
    lab = load_lab()
    inventory = build_inventory(lab)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("---\n")
        f.write("# AUTO-GENERATED by scripts/generate-inventory.py\n")
        f.write("# Do not edit manually. Update config/lab.yml and re-run this script.\n\n")
        yaml.dump(inventory, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    print(f"OK: wrote inventory to {OUTPUT}")
    print(f"    Servers: {len(lab['servers'])}")
    for s in lab["servers"]:
        print(f"      - {s['hostname']} ({s['ip']}) -> {', '.join(s.get('roles', []))}")


if __name__ == "__main__":
    main()
